#!/bin/bash

# NOTES: I'm starting to think that I should use something more than
# just a diff of sorted files... large changes in files, such as
# adding or removing several, could make a mess of reporting.  But
# maybe at that point it doesn't matter... all you really need to know
# is that something changed.x

# report on changes to specified files from day to day

# to see all files freely, this probably needs to run as root.  You
# can run it as an unpriviledged user, but you'll have to verify that
# the user can read all the necessary paths.

# I'm going to rotate the logs here instead of letting logrotate do
# it, since we depend on always comparing to the last good
# log... logrotate just seems to complicate things

logkeepdays=7

appname=monitorfiles

# keep everything in the repo directory
confdir=/etc/$appname
logdir=/var/log/$appname

# use a timestamp with minutes so we can run multiple times a day if
# we want; do this here so that we get the same time across all logs
# instead of updating the time for every directory, etc.
timestamp=$(date +%Y%m%d%H%M)

if [[ ! -e $logdir ]]; then
    mkdir -p $logdir || { echo "ERROR: Cannot create $logdir"; exit 100; }
fi

# find the first file list data file in the 'path'
# these are in reverse order of preference, as the loop won't
# abort... it will just return the *last* file found.
dirfiles=(
    "$confdir/dirlist.conf"
    'dirlist.conf'
)

exclfiles=(
    "$confdir/exclude.conf"
    'exclude.conf'
)

dirlistdat='';
for fn in ${dirfiles[@]}; do
    if [[ -r $fn ]]; then
        dirlistdat=$fn
    fi
done

excllistdat='';
for fn in ${exclfiles[@]}; do
    if [[ -r $fn ]]; then
        excllistdat=$fn
    fi
done

if [[ -z $dirlistdat ]]; then
    echo "ERROR: Cannot find a directory list."
    exit 100
fi

# get the list of directories to check
if [[ -f $dirlistdat && -r $dirlistdat ]]; then
    dirlist=( $(<$dirlistdat) )
else
    echo "ERROR: Cannot read $dirlistdat"
    exit 110
fi

# build exclude pattern...
# if [[ -f $dirlistdat && -r $dirlistdat ]]; then
#     dirlist=( $(<$dirlistdat) )
# else
#     echo "ERROR: Cannot read $dirlistdat"
#     exit 110
# fi

# take a snapshot of each directory
for fn in "${dirlist[@]}"; do
    if [[ -r $fn ]]; then
        logfile=$logdir/${fn//\//_}.log
        find $fn -type f -o -type d |xargs stat -c '%n %a %U:%G %Z %s' >$logfile

        # now compare today's snapshot with the previous snapshot
        lastfile=$(ls -t $logfile-* |head -n1)
        diff $lastfile $logfile
        mv $logfile $logfile-$timestamp
    else
        echo "WARNING: Cannot open $fn" >&2
        # don't exit on warning
    fi

done

# clean up snapshots older than threshold
find $logdir -name '*.log-*' -mtime +$logkeepdays -daystart \
    |xargs --no-run-if-empty rm

exit
 
